name: dart_cef
description: Flutter webview backed by CEF (Chromium Embedded Framework)
version: 0.0.1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  context_menus: ^1.0.2
  window_manager: ^0.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: DartCefPlugin
      linux:
        pluginClass: DartCefPlugin
      windows:
        pluginClass: DartCefPluginCApi
